version: '3.1'

services:

  postgres_db:
    container_name: postgres_db
    image: library/postgres:13
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "demo_project"
    ports:
      - "5444:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/